# docker-compose.yml version: '3.8' requires docker engine 19.03.0+
#Docker compose will set the host name of the containers it creates to the name of the container found in docker-compose.yml: {server, database}. 
version: "3.8"
services:
  database:
    image: postgres
    restart: always
    env_file:
      - fib.env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: fib.env
    depends_on:
      - database
    links:
      - database
    networks:
      - default
    ports:
    - "8080:8080"
volumes:
  data:
